spring.application.name=studentmanger

spring.datasource.url=jdbc:mysql://localhost:3306/studentmanagerapplication
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#to show the sql queries execution
spring.jpa.show-sql = true

# to only update newly created data in database
spring.jpa.hibernate.ddl-auto=update
